Ok element handling.
Juniper/go-netconf pull request #85
Opened 2019-03-22 12:35 UTC by snar

Use boolean pointer to indicate if <ok/> element present in reply.

2019-09-28 10:59 UTC, blib commented
Any chance that will be merged any time soon?

2022-07-22 20:10 UTC, nemith requested changes

2022-07-22 20:10 UTC, nemith commented on netconf/rpc.go
> +	OkPtr     *bool      `xml:"ok,omitempty"`
This should really be hidden inside a custom UnmarshalXML on the function or a custom type.   Either way OkPtr shouldn't be exposed.

See how i implemented this for v2 (may change):  

https://github.com/nemith/go-netconf/blob/v2/msg.go#L102

2022-10-25 21:28 UTC, nemith commented
Closing due to age.

2022-10-25 21:28 UTC, closed without merging